Update workflow

diff --git a/.github/workflows/callable.changelog.yml b/.github/workflows/callable.changelog.yml
--- a/.github/workflows/callable.changelog.yml
+++ b/.github/workflows/callable.changelog.yml
@@ -14,75 +14,79 @@ permissions:
 jobs:
   create_tag:
     runs-on: ubuntu-latest
-    run: |
-      TAG_VERSION=${{ github.event.inputs.name }}
-      git tag $TAG_VERSION
-      git push origin $TAG_VERSION
+    steps:
+      - name: create tag
+        run: |
+          TAG_VERSION=${{ github.event.inputs.name }}
+          git tag $TAG_VERSION
+          git push origin $TAG_VERSION
 
   export_changelog:
     needs: create_tag
     shell: bash
     env:
       TARGET_VERSION: ${{ github.event.inputs.name }}
-    run: |
-      if [ -z "${TARGET_VERSION}" ]; then
-        echo "Error: TARGET_VERSION is not set"
-        exit 1
-      fi
-
-      file="CHANGELOG.md"
-      if [ ! -f "$file" ]; then
-          echo "File not found: $file"
-          exit 1
-      fi
-
-      capturing=false
-      content=""
-      while IFS= read -r line; do
-          if [[ $line == \#\#* ]]; then
-              version=$(echo "$line" | sed 's/^## //')
-              if [[ $version == $TARGET_VERSION ]]; then
-                  capturing=true
-                  content="$line"
-              elif $capturing; then
-                  break
-              fi
-          elif $capturing; then
-              content+=$'\n'"$line"
+    steps:
+      - name: export change and create temp file
+        run: |
+          if [ -z "${TARGET_VERSION}" ]; then
+            echo "Error: TARGET_VERSION is not set"
+            exit 1
           fi
-      done < "$file"
-
-      # After loop, check if capturing is still true to handle the case of single version
-      if $capturing; then
-          echo -e "$content" > CHANGELOG_temp.md
-          echo "Content written to CHANGELOG_temp.md"
-      else
-          # If capturing is false, check if the TARGET_VERSION was found
-          found_version=false
+    
+          file="CHANGELOG.md"
+          if [ ! -f "$file" ]; then
+              echo "File not found: $file"
+              exit 1
+          fi
+    
+          capturing=false
+          content=""
           while IFS= read -r line; do
               if [[ $line == \#\#* ]]; then
                   version=$(echo "$line" | sed 's/^## //')
                   if [[ $version == $TARGET_VERSION ]]; then
-                      found_version=true
                       capturing=true
                       content="$line"
+                  elif $capturing; then
                       break
                   fi
+              elif $capturing; then
+                  content+=$'\n'"$line"
               fi
           done < "$file"
-
+    
+          # After loop, check if capturing is still true to handle the case of single version
           if $capturing; then
               echo -e "$content" > CHANGELOG_temp.md
               echo "Content written to CHANGELOG_temp.md"
           else
-              if $found_version; then
-                  echo "No content found after $TARGET_VERSION in $file"
+              # If capturing is false, check if the TARGET_VERSION was found
+              found_version=false
+              while IFS= read -r line; do
+                  if [[ $line == \#\#* ]]; then
+                      version=$(echo "$line" | sed 's/^## //')
+                      if [[ $version == $TARGET_VERSION ]]; then
+                          found_version=true
+                          capturing=true
+                          content="$line"
+                          break
+                      fi
+                  fi
+              done < "$file"
+    
+              if $capturing; then
+                  echo -e "$content" > CHANGELOG_temp.md
+                  echo "Content written to CHANGELOG_temp.md"
               else
-                  echo "Target version not found in $file"
+                  if $found_version; then
+                      echo "No content found after $TARGET_VERSION in $file"
+                  else
+                      echo "Target version not found in $file"
+                  fi
+                  exit 1
               fi
-              exit 1
           fi
-      fi
 
   generate_release:
       needs: export_changelog
